spring:
  profiles:
    active: dev

user:
  name: someone
  sex: male
  address: fuzhou of china
#pageHepler分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql