server:
  port: 8088
  servlet: #2.0版本context-path配置变更了
     context-path: /springboot


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: stn
    password: 123456

  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: 50ms
        max-idle: 8
    timeout: 50ms
    # （普通集群，不使用则不用开启）在群集中执行命令时要遵循的最大重定向数目。
   # cluster:
     # max-redirects:
    # （普通集群，不使用则不用开启）以逗号分隔的“主机：端口”对列表进行引导。
   #   nodes: 127.0.0.1:1001,127.0.0.1:1002
   # password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


